#!/usr/bin/python3

import argparse

parser = argparse.ArgumentParser(description='Search for words inclusing partial word')
parser.add_argument('snippet', help='patial (or complete string to search for')

args = parser.parse_args()
snippet = args.snippet.lower()

words = open('/usr/share/dict/words').readlines()

print([word.strip() for word in words if snippet in word.lower()])
